### PR TITLE
Handle special permissions correctly when requesting multiple permissions

### LINKED ISSUE #539: [Reply already submitted] java.lang.IllegalStateException: Reply already submitted
After the add, this Permission manage external storage I got the below error any can help me?
Screenshot 2021-04-29 at 5 07 17 PM

[        ] E/AndroidRuntime( 9539): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=210, result=0,
data=null} to activity {com.rbeat/io.flutter.embedding.android.FlutterActivity}: java.lang.IllegalStateException: Reply already submitted
[        ] E/AndroidRuntime( 9539):     at android.app.ActivityThread.deliverResults(ActivityThread.java:5213)
[        ] E/AndroidRuntime( 9539):     at android.app.ActivityThread.handleSendResult(ActivityThread.java:5254)
[        ] E/AndroidRuntime( 9539):     at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
[        ] E/AndroidRuntime( 9539):     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
[        ] E/AndroidRuntime( 9539):     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
[        ] E/AndroidRuntime( 9539):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2246)
[        ] E/AndroidRuntime( 9539):     at android.os.Handler.dispatchMessage(Handler.java:106)
[        ] E/AndroidRuntime( 9539):     at android.os.Looper.loop(Looper.java:233)
[        ] E/AndroidRuntime( 9539):     at android.app.ActivityThread.main(ActivityThread.java:8010)
[        ] E/AndroidRuntime( 9539):     at java.lang.reflect.Method.invoke(Native Method)
[        ] E/AndroidRuntime( 9539):     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
[        ] E/AndroidRuntime( 9539):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
[        ] E/AndroidRuntime( 9539): Caused by: java.lang.IllegalStateException: Reply already submitted
[        ] E/AndroidRuntime( 9539):     at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:155)
[        ] E/AndroidRuntime( 9539):     at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:238)
[        ] E/AndroidRuntime( 9539):     at com.baseflow.permissionhandler.-$$Lambda$fOfJ7OpNBkhP48Mtzqs01exhUJs.onSuccess(Unknown Source:2)
[        ] E/AndroidRuntime( 9539):     at com.baseflow.permissionhandler.PermissionManager.onActivityResult(PermissionManager.java:64)
[        ] E/AndroidRuntime( 9539):     at
io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistr
y.java:739)
[        ] E/AndroidRuntime( 9539):     at
io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:426)
[        ] E/AndroidRuntime( 9539):     at
io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:677)
[        ] E/AndroidRuntime( 9539):     at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:616)
[        ] E/AndroidRuntime( 9539):     at android.app.Activity.dispatchActivityResult(Activity.java:8316)
[        ] E/AndroidRuntime( 9539):     at android.app.ActivityThread.deliverResults(ActivityThread.java:5206)
[        ] E/AndroidRuntime( 9539):     ... 11 more
[  +27 ms] I/Process ( 9539): Sending signal. PID: 9539 SIG: 9

### PR DESCRIPTION
**Pull request by JeroenWeener**
# Context
Android distinguishes between [runtime permissions](https://developer.android.com/guide/topics/permissions/overview#runtime) and [special permissions](https://developer.android.com/guide/topics/permissions/overview#special). Runtime permissions give an app additional access to restricted data or let the app perform restricted actions that more substantially affect the system and other apps. These permissions present the user with a dialog where they can choose to grant or deny the permission. Special permissions guard access to system resources that are particularly sensitive or not directly related to user privacy. These permissions are requested by sending an `Intent` to the OS. The OS will open a special settings page where the user can grant the permission. Runtime permission request results will be reported through `onRequestPermissionsResult(int, String[], int[])`, while special permissions request results will be reported through `onActivityResult(int, int, Intent)`.

# Problem statement
Currently, the code submits all permission request results for runtime permissions at the same time, and the results of special permissions separately. This is a mistake, as we can only return the results to Dart once. Instead, we should keep track of the number of pending requests and only return the results once all of them are in. This PR implements exactly that.

Closes #539, #761, #1126

## Pre-launch Checklist

- [x] I made sure the project builds.
- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is does not need version changes.
- [x] I updated `CHANGELOG.md` to add a description of the change.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I rebased onto `main`.
- [ ] I added new tests to check the change I am making, or this PR does not need tests.
- [x] I made sure all existing and new tests are passing.
- [x] I ran `dart format .` and committed any changes.
- [x] I ran `flutter analyze` and fixed any errors.

[Contributor Guide]: https://github.com/Baseflow/flutter-permission-handler/blob/master/CONTRIBUTING.md
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

### CODE REVIEW

**Comment by mkgdev** [comment]
Can this PR merge be expedited as this is causing numerous spurious crashes in production?

**Comment by Adityapanther** [comment]
could you please make it fast, it's a critical issue ?

**Comment by tudang-monstarlab** [comment]
Does anyone still work for this PR 😭 ?

**Comment by JeroenWeener** [comment]
@mkgdev @Adityapanther @tudang-monstarlab we take PR reviews very seriously, as `flutter-permission-handler` is a sophisticated plugin on which a lot of developers depend. Reviewing takes some time, although usually only about a week. The PR has been open for less than a week at the time of writing, so I want to ask you all to exert some patience 😉

**Comment by Adityapanther** [comment]
@JeroenWeener the production app is dying. The user is leaving our app 😭.

**Comment by Adityapanther** [comment]
Could you please make it some faster ?

**Comment by JeroenWeener** [comment]
@Adityapanther this bug has been present for a long time, so I do not see why this should be critical. If your application cannot wait, I suggest you request permissions one by one for now.

**Comment by tudang-monstarlab** [comment]
@JeroenWeener 
Thanks for your response👍. this bug is happening on our client devices 😭 . 
Very happy to hear that it could be processed around a week 🙇 .
It helps me answer my client in the meantime🙇 .

**Review by mvanbeusekom — CHANGES_REQUESTED** [review]
The concept of this looks very nice, however I feel there is a potential change for threading errors. I provided a comment with a possible solution.

File: permission_handler_android/android/src/main/java/com/baseflow/permissionhandler/PermissionManager.java [hunk 1]
```diff
@@ -35,6 +36,23 @@ final class PermissionManager implements PluginRegistry.ActivityResultListener,
...
     private Activity activity;
 
+    /**
+     * The number of pending permission requests.
+     * <p>
+     * This number is set by {@link this#requestPermissions(List, Activity, RequestPermissionsSuccessCallback, ErrorCallback)}
+     * and then reduced when receiving results in {@link this#onActivityResult(int, int, Intent)}
+     * and {@link this#onRequestPermissionsResult(int, String[], int[])}.
+     */
+    private int pendingRequestCount;
```
[the remark this answers is not in the document]
Comment (JeroenWeener) [reply permission_handler_android/android/src/main/java/com/baseflow/permissionhandler/PermissionManager.java:46]: I believe this code does not have to be thread-safe, as all interactions with `pendingRequestCount` are being run on the UI-thread.

File: permission_handler_android/android/src/main/java/com/baseflow/permissionhandler/PermissionManager.java [hunk 2]
```diff
@@ -262,44 +319,50 @@ void requestPermissions(
                 continue;
             }
 
+            // Request special permissions.
             if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M && permission == PermissionConstants.PERMISSION_GROUP_IGNORE_BATTERY_OPTIMIZATIONS) {
                 executeIntent(
                         Settings.ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS,
                         PermissionConstants.PERMISSION_CODE_IGNORE_BATTERY_OPTIMIZATIONS);
+                pendingRequestCount++;
```
Comment (mvanbeusekom) [inline permission_handler_android/android/src/main/java/com/baseflow/permissionhandler/PermissionManager.java:327]: Won't it be better to place this line inside the `executeIntent` method, that way we don't have to repeat it and would also ensure it is incremented when new permissions are added.

**Review by mvanbeusekom — CHANGES_REQUESTED** [review]

File: permission_handler_android/android/src/main/java/com/baseflow/permissionhandler/PermissionManager.java (hunk 2 above)
Comment (JeroenWeener) [reply permission_handler_android/android/src/main/java/com/baseflow/permissionhandler/PermissionManager.java:327]: I'm a bit hesitant to do that, as the method name does not imply any side-effects. Also, there are two methods that would need to do this (`executeSimpleIntent` as well). Can we think of a cleaner way to handle this? Maybe we could refactor the methods to a single method called `launchSpecialPermission`. We could add documentation about the special special case for `NOTIFICATION_POLICY_ACCESS`. The bookkeeping makes a little more sense in such a method, as the name implies that it considers launching a permission.

Comment (mvanbeusekom) [reply permission_handler_android/android/src/main/java/com/baseflow/permissionhandler/PermissionManager.java:327]: Agreed, lets go for the refactor version. I think it will be worth as it potentially will prevent bugs when new permissions are added.

**Review by mvanbeusekom — APPROVED** [review]
LGTM, can be merged when the conflicts have been resolved.
