### PR TITLE
Fix deprecation warning on iOS using phone permissions.

### LINKED ISSUE #597: /Users/s2yed/.pub-cache/hosted/pub.dartlang.org/permission_handler-8.1.0/ios/Classes/strategies/PhonePermissionStrategy.m:41:16: warning: incompatible pointer types initializing 'CTCarrier *' with an expression of type 'NSDictionary<NSString *,CTCarrier *> * _Nullable' [-Wincompatible-pointer-types]
/Users/s2yed/.pub-cache/hosted/pub.dartlang.org/permission_handler-8.1.0/ios/Classes/strategies/PhonePermissionStrategy.m:41:16: warning: incompatible pointer types initializing 'CTCarrier *' with an expression of type 'NSDictionary<NSString *,CTCarrier *> * _Nullable' [-Wincompatible-pointer-types]

### PR DESCRIPTION
**Pull request by mvanbeusekom**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)

Bug fix

### :arrow_heading_down: What is the current behavior?

The permission_handler uses the `[CTTelephonyNetworkInfo subscriberCellularProvider]` [SDK](https://developer.apple.com/documentation/coretelephony/cttelephonynetworkinfo/1616900-subscribercellularprovider?language=objc) to test if the device is capable of placing phone calls. However this method has been deprecated since iOS 12.

### :new: What is the new behavior (if this is a feature change)?

Use the `[CTTelephonyNetworkInfo serviceSubscriberCellularProviders]` [SDK](https://developer.apple.com/documentation/coretelephony/cttelephonynetworkinfo/3024511-servicesubscribercellularprovide?language=objc) when running on iOS 12 or higher.

### :boom: Does this PR introduce a breaking change?

No

### :bug: Recommendations for testing

Run the example App on iOS 12 or higher and look for deprecation warnings in the log.

### :memo: Links to relevant issues/docs

- Fixes #597

### :thinking: Checklist before submitting

- [x] I made sure all projects build.
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy](https://dart.dev/tools/pub/versioning).
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I followed the style guide lines ([code style guide](https://github.com/Baseflow/flutter-permission-handler/blob/master/CONTRIBUTING.md)).
- [x] I updated the relevant documentation.
- [x] I rebased onto current `master`.

### CODE REVIEW

File: permission_handler/ios/Classes/strategies/PhonePermissionStrategy.m [hunk 1]
```diff
@@ -13,40 +13,55 @@
...
+-(bool)canPlacePhoneCallWithCarrier:(CTCarrier *)carrier {
+  // https://stackoverflow.com/a/11595365
+  NSString *mnc = [carrier mobileNetworkCode];
+  if (([mnc length] == 0) || ([mnc isEqualToString:@"65535"])) {
+    // Device cannot place a call at this time.  SIM might be removed.
+    return NO;
+  } else {
+    // Device can place a phone call
+    return YES;
+  }
```
Comment (renefloor) [inline permission_handler/ios/Classes/strategies/PhonePermissionStrategy.m:64]: Why not just:
```suggestion
  return !([mnc length] == 0) || ([mnc isEqualToString:@"65535"]);
```

**Review by renefloor — APPROVED** [review]

File: permission_handler/ios/Classes/strategies/PhonePermissionStrategy.m (hunk 1 above)
Comment (mvanbeusekom) [reply permission_handler/ios/Classes/strategies/PhonePermissionStrategy.m:64]: First off all, the current version was copied straight from SO and I didn't look to much at the code (except from figuring out where the `65535` literal came from).

But having a closer look at it, I prefer the current version because it is a bit more readable. The `!` makes it a bit more cryptic and that much harder to see what is actually going on.
