### PR TITLE
Return 'permanently denied' as permission status

### LINKED ISSUE #936: Permission.microphone.status returns denied when it should be permanentlyDenied
## 🐛 Bug Report

only on Android
the user permanentlyDenied the permission but the `get status` is returning denied.

### Expected behavior
the `get status` should return permanentlyDenied.

### Reproduction steps

deny the microphone permission twice. 
run `Permission.microphone.status` and see that the status is denied
run `Permission.microphone.request()` and see that the status is permanentlyDenied

### Configuration
-

**Version:** 9.2.0

**Platform:** 
- [ ] :iphone: iOS
- [X] :robot: Android

### PR DESCRIPTION
**Pull request by JeroenWeener**
Currently there is a discrepancy between a permission's status and its request result. Permission statuses are always 'denied', even if the request result is 'permanently denied'. This PR fixes that bug by leveraging the logic added in #1125.

@mvanbeusekom do you agree that a permission's status should be able to return 'permanently denied'? I noticed statuses can also return 'restricted', so maybe you want to treat a permission's status and its request result differently? On iOS, the status always returns 'permanently denied' (note that permissions can only be asked once on iOS).
@mvanbeusekom should this change be labeled as breaking? Some folks might be depending on the exact return value of a permission's status.

This PR fixes #936. Note that the mentioned issue does not seem to be particular to only the microphone permission, but rather, all permissions that show the user a dialog (so not the ones that open the settings page).

## Pre-launch Checklist

- [x] I made sure the project builds.
- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is does not need version changes.
- [x] I updated `CHANGELOG.md` to add a description of the change.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I rebased onto `main`.
- [ ] I added new tests to check the change I am making, or this PR does not need tests.
- [x] I made sure all existing and new tests are passing.
- [x] I ran `dart format .` and committed any changes.
- [x] I ran `flutter analyze` and fixed any errors.

[Contributor Guide]: https://github.com/Baseflow/flutter-permission-handler/blob/master/CONTRIBUTING.md
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

### CODE REVIEW

File: permission_handler_android/android/src/main/java/com/baseflow/permissionhandler/PermissionManager.java [hunk 1]
```diff
@@ -306,25 +311,25 @@ void requestPermissions(
     @PermissionConstants.PermissionStatus
     private int determinePermissionStatus(
             @PermissionConstants.PermissionGroup int permission,
-            Context context) {
+            Activity activity) {
```
Comment (mvanbeusekom) [inline permission_handler_android/android/src/main/java/com/baseflow/permissionhandler/PermissionManager.java:314]: This change might result into issue because the `activity` might be `null` in certain conditions (e.g. when the app is running in the background). 

I noticed this method uses the activity a few times without making sure it is not `null` which will result into runtime exceptions. I think we should provide an alternative solution, maybe using casting where we validate if the supplied `context` is of type `Activity` and if so do more advanced status validation, if not stick to the current implementation.

**Review by mvanbeusekom — CHANGES_REQUESTED** [review]
Hi @JeroenWeener,

Thanks for this PR. If we can be sure the returning the `permanentlyDenied` status works reliable than that would be a great addition and would help a lot of users. So yes, this would be great. This should however be considered a breaking change. Like you mentioned we should assume there are apps that apply won't handle `permanentlyDenied` status on Android.

I have also added one concern about updating the `Context context` parameter of the `checkPermissionStatus` method, please have a look at this.

**Review by mvanbeusekom — APPROVED** [review]
LGTM, however lets first merge in pr #1139

**Comment by jjoelson** [comment]
Hi @JeroenWeener and @mvanbeusekom!

Here is a useful writeup from the `geolocator` package's wiki that explains why they don't feel they can reliably distinguish between denied and permanently denied: https://github.com/Baseflow/flutter-geolocator/wiki/Breaking-changes-in-7.0.0#android-permission-update

The full writeup is worth reading, but the long and short of it is that since the "Ask every time" option was added in Android API 30, the user manually selecting that option in settings will break the denied vs permanently denied logic.

The `permission_handler` package itself referenced that write up in its [6.0.0 change notes](https://github.com/Baseflow/flutter-permission-handler/wiki/Changes-in-6.0.0) and says the following: 
> In the old implementation permission_handler saved the status in Android's Shared Preferences to determine if the permission was permanently denied. The implementation now does not save this info, so this needs to be checked twice, to determine permanently denied permissions.

Has something changed since then to enable this package to reliably distinguish denied vs permanently denied, or is the implementation in this PR vulnerable to the same bug described in the above writeup?

Tomorrow or next week I can do some tests with the latest `permission_handler` to see if any bugs crop up relating to this change, but I just wanted to put this on your radar.

**Comment by JeroenWeener** [comment]
Hi @jjoelson thank you for bringing this up!

I was unaware of this history of the `geolocator` when I worked on this issue. What I get from the wiki is that the solution is slightly different. I have experimentally tested the changes made in this PR back then. A short write-up is available in the code: https://github.com/Baseflow/flutter-permission-handler/blob/384fc9ea32d2db0ba84d2983ab0bfe62ec850e19/permission_handler_android/android/src/main/java/com/baseflow/permissionhandler/PermissionUtils.java#L399-L458

I am very interested in your test results to see if you can verify correct behavior 🙌

**Comment by jjoelson** [comment]
Hi @JeroenWeener! I did some testing and unfortunately I did encounter the bug. I filed a new issue here with repro steps: https://github.com/Baseflow/flutter-permission-handler/issues/1206

**Comment by maquejp** [comment]
Hello, 
The bug is still there... Any idea when you can work on it?

 checkPermission: LocationPermission.denied requestPermission: LocationPermission.deniedForever
 
Thank you.

**Comment by mvanbeusekom** [comment]
Hello @maquejp, 

As mentioned by Jeroen Weener this is not a bug, rather a limitation of Android. You can also read our reasoning to this in our Geolocator post: https://github.com/Baseflow/flutter-geolocator/wiki/Breaking-changes-in-7.0.0#android-permission-update (also mentioned in the comment from jjoelson.
